"""Migracion inicial DDD

Revision ID: 019f010cd755
Revises: 
Create Date: 2026-01-19 16:04:04.528679
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '019f010cd755'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('intentos_login', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_activo'), 'usuarios', ['activo'], unique=False)
    op.create_index(op.f('ix_usuarios_eliminado'), 'usuarios', ['eliminado'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('categorias_partida',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_partida_activo'), 'categorias_partida', ['activo'], unique=False)
    op.create_index(op.f('ix_categorias_partida_codigo'), 'categorias_partida', ['codigo'], unique=True)
    op.create_index(op.f('ix_categorias_partida_eliminado'), 'categorias_partida', ['eliminado'], unique=False)
    op.create_table('configuraciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modificable', sa.Boolean(), nullable=False),
    sa.Column('grupo', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuraciones_clave'), 'configuraciones', ['clave'], unique=True)
    op.create_index(op.f('ix_configuraciones_eliminado'), 'configuraciones', ['eliminado'], unique=False)
    op.create_table('donaciones_conceptos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donaciones_conceptos_activo'), 'donaciones_conceptos', ['activo'], unique=False)
    op.create_index(op.f('ix_donaciones_conceptos_codigo'), 'donaciones_conceptos', ['codigo'], unique=True)
    op.create_index(op.f('ix_donaciones_conceptos_eliminado'), 'donaciones_conceptos', ['eliminado'], unique=False)
    op.create_table('estados_campania',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_campania_activo'), 'estados_campania', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_campania_codigo'), 'estados_campania', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_campania_eliminado'), 'estados_campania', ['eliminado'], unique=False)
    op.create_table('estados_cuota',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_cuota_activo'), 'estados_cuota', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_cuota_codigo'), 'estados_cuota', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_cuota_eliminado'), 'estados_cuota', ['eliminado'], unique=False)
    op.create_table('estados_donacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_donacion_activo'), 'estados_donacion', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_donacion_codigo'), 'estados_donacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_donacion_eliminado'), 'estados_donacion', ['eliminado'], unique=False)
    op.create_table('estados_orden_cobro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_orden_cobro_activo'), 'estados_orden_cobro', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_orden_cobro_codigo'), 'estados_orden_cobro', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_orden_cobro_eliminado'), 'estados_orden_cobro', ['eliminado'], unique=False)
    op.create_table('estados_participante',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_participante_activo'), 'estados_participante', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_participante_codigo'), 'estados_participante', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_participante_eliminado'), 'estados_participante', ['eliminado'], unique=False)
    op.create_table('estados_planificacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_planificacion_activo'), 'estados_planificacion', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_planificacion_codigo'), 'estados_planificacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_planificacion_eliminado'), 'estados_planificacion', ['eliminado'], unique=False)
    op.create_table('estados_remesa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_remesa_activo'), 'estados_remesa', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_remesa_codigo'), 'estados_remesa', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_remesa_eliminado'), 'estados_remesa', ['eliminado'], unique=False)
    op.create_table('estados_tarea',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('es_inicial', sa.Boolean(), nullable=False),
    sa.Column('es_final', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_tarea_activo'), 'estados_tarea', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_tarea_codigo'), 'estados_tarea', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_tarea_eliminado'), 'estados_tarea', ['eliminado'], unique=False)
    op.create_table('historial_estados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=100), nullable=False),
    sa.Column('estado_anterior_codigo', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo_codigo', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_eliminado'), 'historial_estados', ['eliminado'], unique=False)
    op.create_index(op.f('ix_historial_estados_entidad_id'), 'historial_estados', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_historial_estados_entidad_tipo'), 'historial_estados', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_historial_estados_fecha_cambio'), 'historial_estados', ['fecha_cambio'], unique=False)
    op.create_table('historial_seguridad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evento_tipo', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos_adicionales', sa.Text(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('codigo_error', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_seguridad_eliminado'), 'historial_seguridad', ['eliminado'], unique=False)
    op.create_index(op.f('ix_historial_seguridad_evento_tipo'), 'historial_seguridad', ['evento_tipo'], unique=False)
    op.create_index(op.f('ix_historial_seguridad_fecha_evento'), 'historial_seguridad', ['fecha_evento'], unique=False)
    op.create_index(op.f('ix_historial_seguridad_ip_address'), 'historial_seguridad', ['ip_address'], unique=False)
    op.create_index(op.f('ix_historial_seguridad_usuario_id'), 'historial_seguridad', ['usuario_id'], unique=False)
    op.create_table('importes_cuota_anio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ejercicio', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importes_cuota_anio_ejercicio'), 'importes_cuota_anio', ['ejercicio'], unique=True)
    op.create_index(op.f('ix_importes_cuota_anio_eliminado'), 'importes_cuota_anio', ['eliminado'], unique=False)
    op.create_table('intentos_acceso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identificador', sa.String(length=200), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha_intento', sa.DateTime(), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('motivo_fallo', sa.String(length=200), nullable=True),
    sa.Column('bloqueado_tras_intento', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_acceso_eliminado'), 'intentos_acceso', ['eliminado'], unique=False)
    op.create_index(op.f('ix_intentos_acceso_exitoso'), 'intentos_acceso', ['exitoso'], unique=False)
    op.create_index(op.f('ix_intentos_acceso_fecha_intento'), 'intentos_acceso', ['fecha_intento'], unique=False)
    op.create_index(op.f('ix_intentos_acceso_identificador'), 'intentos_acceso', ['identificador'], unique=False)
    op.create_index(op.f('ix_intentos_acceso_ip_address'), 'intentos_acceso', ['ip_address'], unique=False)
    op.create_index(op.f('ix_intentos_acceso_usuario_id'), 'intentos_acceso', ['usuario_id'], unique=False)
    op.create_table('ips_bloqueadas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('fecha_bloqueo', sa.DateTime(), nullable=False),
    sa.Column('fecha_desbloqueo', sa.DateTime(), nullable=True),
    sa.Column('bloqueado_permanente', sa.Boolean(), nullable=False),
    sa.Column('bloqueado_por_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bloqueado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ips_bloqueadas_eliminado'), 'ips_bloqueadas', ['eliminado'], unique=False)
    op.create_index(op.f('ix_ips_bloqueadas_fecha_desbloqueo'), 'ips_bloqueadas', ['fecha_desbloqueo'], unique=False)
    op.create_index(op.f('ix_ips_bloqueadas_ip_address'), 'ips_bloqueadas', ['ip_address'], unique=True)
    op.create_table('paises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('codigo_iso3', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nombre_oficial', sa.String(length=200), nullable=True),
    sa.Column('codigo_telefono', sa.String(length=10), nullable=True),
    sa.Column('continente', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso3')
    )
    op.create_index(op.f('ix_paises_activo'), 'paises', ['activo'], unique=False)
    op.create_index(op.f('ix_paises_codigo'), 'paises', ['codigo'], unique=True)
    op.create_index(op.f('ix_paises_eliminado'), 'paises', ['eliminado'], unique=False)
    op.create_index(op.f('ix_paises_nombre'), 'paises', ['nombre'], unique=False)
    op.create_table('reglas_validacion_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_clave', sa.String(length=100), nullable=False),
    sa.Column('tipo_dato', sa.String(length=50), nullable=False),
    sa.Column('min_valor', sa.Float(), nullable=True),
    sa.Column('max_valor', sa.Float(), nullable=True),
    sa.Column('max_longitud', sa.Integer(), nullable=True),
    sa.Column('decimales', sa.Integer(), nullable=True),
    sa.Column('pattern_regex', sa.String(length=500), nullable=True),
    sa.Column('valores_permitidos', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('mensaje_error', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_validacion_config_config_clave'), 'reglas_validacion_config', ['config_clave'], unique=True)
    op.create_index(op.f('ix_reglas_validacion_config_eliminado'), 'reglas_validacion_config', ['eliminado'], unique=False)
    op.create_table('sesiones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('dispositivo', sa.String(length=100), nullable=True),
    sa.Column('navegador', sa.String(length=100), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=100), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_activa'), 'sesiones', ['activa'], unique=False)
    op.create_index(op.f('ix_sesiones_eliminado'), 'sesiones', ['eliminado'], unique=False)
    op.create_index(op.f('ix_sesiones_fecha_expiracion'), 'sesiones', ['fecha_expiracion'], unique=False)
    op.create_index(op.f('ix_sesiones_refresh_token'), 'sesiones', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_sesiones_token'), 'sesiones', ['token'], unique=True)
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones', ['usuario_id'], unique=False)
    op.create_table('tipos_notificacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('permite_email', sa.Boolean(), nullable=False),
    sa.Column('permite_sms', sa.Boolean(), nullable=False),
    sa.Column('permite_push', sa.Boolean(), nullable=False),
    sa.Column('permite_inapp', sa.Boolean(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('requiere_accion', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('template_asunto', sa.String(length=200), nullable=True),
    sa.Column('template_cuerpo', sa.Text(), nullable=True),
    sa.Column('template_sms', sa.String(length=500), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_notificacion_activo'), 'tipos_notificacion', ['activo'], unique=False)
    op.create_index(op.f('ix_tipos_notificacion_categoria'), 'tipos_notificacion', ['categoria'], unique=False)
    op.create_index(op.f('ix_tipos_notificacion_codigo'), 'tipos_notificacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_notificacion_eliminado'), 'tipos_notificacion', ['eliminado'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_roles_eliminado'), 'usuarios_roles', ['eliminado'], unique=False)
    op.create_index(op.f('ix_usuarios_roles_rol_id'), 'usuarios_roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuarios_roles_usuario_id'), 'usuarios_roles', ['usuario_id'], unique=False)
    op.create_table('cuotas_anuales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('miembro_id', sa.Uuid(), nullable=False),
    sa.Column('ejercicio', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Uuid(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('importe_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_codigo', sa.String(length=50), nullable=False),
    sa.Column('modo_ingreso', sa.Enum('SEPA', 'TRANSFERENCIA', 'PAYPAL', 'EFECTIVO', 'TARJETA', name='modoingreso'), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_cuota.codigo'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuotas_anuales_agrupacion_id'), 'cuotas_anuales', ['agrupacion_id'], unique=False)
    op.create_index(op.f('ix_cuotas_anuales_ejercicio'), 'cuotas_anuales', ['ejercicio'], unique=False)
    op.create_index(op.f('ix_cuotas_anuales_eliminado'), 'cuotas_anuales', ['eliminado'], unique=False)
    op.create_index(op.f('ix_cuotas_anuales_estado_codigo'), 'cuotas_anuales', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_cuotas_anuales_miembro_id'), 'cuotas_anuales', ['miembro_id'], unique=False)
    op.create_table('donaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('miembro_id', sa.Uuid(), nullable=True),
    sa.Column('concepto_id', sa.Uuid(), nullable=True),
    sa.Column('campania_id', sa.Uuid(), nullable=True),
    sa.Column('donante_nombre', sa.String(length=200), nullable=True),
    sa.Column('donante_email', sa.String(length=255), nullable=True),
    sa.Column('donante_telefono', sa.String(length=20), nullable=True),
    sa.Column('donante_dni', sa.String(length=20), nullable=True),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gastos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('modo_ingreso', sa.String(length=50), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('estado_codigo', sa.String(length=50), nullable=False),
    sa.Column('certificado_emitido', sa.Boolean(), nullable=False),
    sa.Column('fecha_certificado', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('anonima', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['donaciones_conceptos.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_donacion.codigo'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donaciones_campania_id'), 'donaciones', ['campania_id'], unique=False)
    op.create_index(op.f('ix_donaciones_concepto_id'), 'donaciones', ['concepto_id'], unique=False)
    op.create_index(op.f('ix_donaciones_eliminado'), 'donaciones', ['eliminado'], unique=False)
    op.create_index(op.f('ix_donaciones_estado_codigo'), 'donaciones', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_donaciones_fecha'), 'donaciones', ['fecha'], unique=False)
    op.create_index(op.f('ix_donaciones_miembro_id'), 'donaciones', ['miembro_id'], unique=False)
    op.create_table('historial_configuracion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('configuracion_id', sa.Uuid(), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=False),
    sa.Column('valor_nuevo', sa.Text(), nullable=False),
    sa.Column('motivo_cambio', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['configuracion_id'], ['configuraciones.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_configuracion_eliminado'), 'historial_configuracion', ['eliminado'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('archivada', sa.Boolean(), nullable=False),
    sa.Column('requiere_accion', sa.Boolean(), nullable=False),
    sa.Column('accion_completada', sa.Boolean(), nullable=True),
    sa.Column('url_accion', sa.String(length=500), nullable=True),
    sa.Column('intentos_envio', sa.Integer(), nullable=False),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.String(length=100), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_notificacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_archivada'), 'notificaciones', ['archivada'], unique=False)
    op.create_index(op.f('ix_notificaciones_canal'), 'notificaciones', ['canal'], unique=False)
    op.create_index(op.f('ix_notificaciones_eliminado'), 'notificaciones', ['eliminado'], unique=False)
    op.create_index(op.f('ix_notificaciones_entidad_id'), 'notificaciones', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_entidad_tipo'), 'notificaciones', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_estado'), 'notificaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_notificaciones_fecha_creacion'), 'notificaciones', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo_id'), 'notificaciones', ['tipo_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('planificaciones_anuales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ejercicio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('objetivos', sa.Text(), nullable=True),
    sa.Column('estado_codigo', sa.String(length=20), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('presupuesto_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_planificacion.codigo'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planificaciones_anuales_ejercicio'), 'planificaciones_anuales', ['ejercicio'], unique=True)
    op.create_index(op.f('ix_planificaciones_anuales_eliminado'), 'planificaciones_anuales', ['eliminado'], unique=False)
    op.create_index(op.f('ix_planificaciones_anuales_estado_codigo'), 'planificaciones_anuales', ['estado_codigo'], unique=False)
    op.create_table('preferencias_notificacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_id', sa.Uuid(), nullable=False),
    sa.Column('email_habilitado', sa.Boolean(), nullable=False),
    sa.Column('sms_habilitado', sa.Boolean(), nullable=False),
    sa.Column('push_habilitado', sa.Boolean(), nullable=False),
    sa.Column('inapp_habilitado', sa.Boolean(), nullable=False),
    sa.Column('frecuencia', sa.String(length=20), nullable=False),
    sa.Column('hora_preferida', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipos_notificacion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_notificacion_eliminado'), 'preferencias_notificacion', ['eliminado'], unique=False)
    op.create_index(op.f('ix_preferencias_notificacion_tipo_id'), 'preferencias_notificacion', ['tipo_id'], unique=False)
    op.create_index(op.f('ix_preferencias_notificacion_usuario_id'), 'preferencias_notificacion', ['usuario_id'], unique=False)
    op.create_table('provincias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pais_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'codigo', name='uq_provincia_pais_codigo')
    )
    op.create_index(op.f('ix_provincias_activo'), 'provincias', ['activo'], unique=False)
    op.create_index(op.f('ix_provincias_codigo'), 'provincias', ['codigo'], unique=False)
    op.create_index(op.f('ix_provincias_eliminado'), 'provincias', ['eliminado'], unique=False)
    op.create_index(op.f('ix_provincias_nombre'), 'provincias', ['nombre'], unique=False)
    op.create_index(op.f('ix_provincias_pais_id'), 'provincias', ['pais_id'], unique=False)
    op.create_table('remesas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('fecha_envio', sa.Date(), nullable=True),
    sa.Column('fecha_cobro', sa.Date(), nullable=False),
    sa.Column('importe_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gastos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('num_ordenes', sa.Integer(), nullable=False),
    sa.Column('estado_codigo', sa.String(length=50), nullable=False),
    sa.Column('archivo_sepa', sa.String(length=500), nullable=True),
    sa.Column('mensaje_id', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_remesa.codigo'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remesas_eliminado'), 'remesas', ['eliminado'], unique=False)
    op.create_index(op.f('ix_remesas_estado_codigo'), 'remesas', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_remesas_fecha_creacion'), 'remesas', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_remesas_referencia'), 'remesas', ['referencia'], unique=True)
    op.create_table('municipios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provincia_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provincia_id', 'codigo', name='uq_municipio_provincia_codigo')
    )
    op.create_index(op.f('ix_municipios_activo'), 'municipios', ['activo'], unique=False)
    op.create_index(op.f('ix_municipios_codigo'), 'municipios', ['codigo'], unique=False)
    op.create_index(op.f('ix_municipios_eliminado'), 'municipios', ['eliminado'], unique=False)
    op.create_index(op.f('ix_municipios_nombre'), 'municipios', ['nombre'], unique=False)
    op.create_index(op.f('ix_municipios_provincia_id'), 'municipios', ['provincia_id'], unique=False)
    op.create_table('ordenes_cobro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remesa_id', sa.Uuid(), nullable=False),
    sa.Column('cuota_id', sa.Uuid(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia_mandato', sa.String(length=100), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('estado_codigo', sa.String(length=50), nullable=False),
    sa.Column('fecha_procesamiento', sa.Date(), nullable=True),
    sa.Column('codigo_rechazo', sa.String(length=50), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuotas_anuales.id'], ),
    sa.ForeignKeyConstraint(['estado_codigo'], ['estados_orden_cobro.codigo'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['remesa_id'], ['remesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_cobro_cuota_id'), 'ordenes_cobro', ['cuota_id'], unique=False)
    op.create_index(op.f('ix_ordenes_cobro_eliminado'), 'ordenes_cobro', ['eliminado'], unique=False)
    op.create_index(op.f('ix_ordenes_cobro_estado_codigo'), 'ordenes_cobro', ['estado_codigo'], unique=False)
    op.create_index(op.f('ix_ordenes_cobro_remesa_id'), 'ordenes_cobro', ['remesa_id'], unique=False)
    op.create_table('partidas_presupuestarias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ejercicio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=True),
    sa.Column('importe_presupuestado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('importe_comprometido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('importe_ejecutado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('planificacion_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_partida.id'], ),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['planificacion_id'], ['planificaciones_anuales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_presupuestarias_activo'), 'partidas_presupuestarias', ['activo'], unique=False)
    op.create_index(op.f('ix_partidas_presupuestarias_categoria_id'), 'partidas_presupuestarias', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_partidas_presupuestarias_codigo'), 'partidas_presupuestarias', ['codigo'], unique=True)
    op.create_index(op.f('ix_partidas_presupuestarias_ejercicio'), 'partidas_presupuestarias', ['ejercicio'], unique=False)
    op.create_index(op.f('ix_partidas_presupuestarias_eliminado'), 'partidas_presupuestarias', ['eliminado'], unique=False)
    op.create_index(op.f('ix_partidas_presupuestarias_planificacion_id'), 'partidas_presupuestarias', ['planificacion_id'], unique=False)
    op.create_index(op.f('ix_partidas_presupuestarias_tipo'), 'partidas_presupuestarias', ['tipo'], unique=False)
    op.create_table('direcciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('via_tipo', sa.String(length=20), nullable=True),
    sa.Column('via_nombre', sa.String(length=200), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('piso', sa.String(length=10), nullable=True),
    sa.Column('puerta', sa.String(length=10), nullable=True),
    sa.Column('bloque', sa.String(length=10), nullable=True),
    sa.Column('escalera', sa.String(length=10), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=True),
    sa.Column('provincia_id', sa.Uuid(), nullable=False),
    sa.Column('pais_id', sa.Uuid(), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('coordenadas_lat', sa.String(length=50), nullable=True),
    sa.Column('coordenadas_lon', sa.String(length=50), nullable=True),
    sa.Column('validada', sa.Integer(), nullable=False),
    sa.Column('fecha_validacion', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_codigo_postal'), 'direcciones', ['codigo_postal'], unique=False)
    op.create_index(op.f('ix_direcciones_eliminado'), 'direcciones', ['eliminado'], unique=False)
    op.create_index(op.f('ix_direcciones_municipio_id'), 'direcciones', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_direcciones_pais_id'), 'direcciones', ['pais_id'], unique=False)
    op.create_index(op.f('ix_direcciones_provincia_id'), 'direcciones', ['provincia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direcciones_provincia_id'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_pais_id'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_municipio_id'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_eliminado'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_codigo_postal'), table_name='direcciones')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_partidas_presupuestarias_tipo'), table_name='partidas_presupuestarias')
    op.drop_index(op.f('ix_partidas_presupuestarias_planificacion_id'), table_name='partidas_presupuestarias')
    op.drop_index(op.f('ix_partidas_presupuestarias_eliminado'), table_name='partidas_presupuestarias')
    op.drop_index(op.f('ix_partidas_presupuestarias_ejercicio'), table_name='partidas_presupuestarias')
    op.drop_index(op.f('ix_partidas_presupuestarias_codigo'), table_name='partidas_presupuestarias')
    op.drop_index(op.f('ix_partidas_presupuestarias_categoria_id'), table_name='partidas_presupuestarias')
    op.drop_index(op.f('ix_partidas_presupuestarias_activo'), table_name='partidas_presupuestarias')
    op.drop_table('partidas_presupuestarias')
    op.drop_index(op.f('ix_ordenes_cobro_remesa_id'), table_name='ordenes_cobro')
    op.drop_index(op.f('ix_ordenes_cobro_estado_codigo'), table_name='ordenes_cobro')
    op.drop_index(op.f('ix_ordenes_cobro_eliminado'), table_name='ordenes_cobro')
    op.drop_index(op.f('ix_ordenes_cobro_cuota_id'), table_name='ordenes_cobro')
    op.drop_table('ordenes_cobro')
    op.drop_index(op.f('ix_municipios_provincia_id'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_nombre'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_eliminado'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_codigo'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_activo'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_remesas_referencia'), table_name='remesas')
    op.drop_index(op.f('ix_remesas_fecha_creacion'), table_name='remesas')
    op.drop_index(op.f('ix_remesas_estado_codigo'), table_name='remesas')
    op.drop_index(op.f('ix_remesas_eliminado'), table_name='remesas')
    op.drop_table('remesas')
    op.drop_index(op.f('ix_provincias_pais_id'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_nombre'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_eliminado'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_codigo'), table_name='provincias')
    op.drop_index(op.f('ix_provincias_activo'), table_name='provincias')
    op.drop_table('provincias')
    op.drop_index(op.f('ix_preferencias_notificacion_usuario_id'), table_name='preferencias_notificacion')
    op.drop_index(op.f('ix_preferencias_notificacion_tipo_id'), table_name='preferencias_notificacion')
    op.drop_index(op.f('ix_preferencias_notificacion_eliminado'), table_name='preferencias_notificacion')
    op.drop_table('preferencias_notificacion')
    op.drop_index(op.f('ix_planificaciones_anuales_estado_codigo'), table_name='planificaciones_anuales')
    op.drop_index(op.f('ix_planificaciones_anuales_eliminado'), table_name='planificaciones_anuales')
    op.drop_index(op.f('ix_planificaciones_anuales_ejercicio'), table_name='planificaciones_anuales')
    op.drop_table('planificaciones_anuales')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_fecha_creacion'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_estado'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_entidad_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_entidad_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_eliminado'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_canal'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_archivada'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_historial_configuracion_eliminado'), table_name='historial_configuracion')
    op.drop_table('historial_configuracion')
    op.drop_index(op.f('ix_donaciones_miembro_id'), table_name='donaciones')
    op.drop_index(op.f('ix_donaciones_fecha'), table_name='donaciones')
    op.drop_index(op.f('ix_donaciones_estado_codigo'), table_name='donaciones')
    op.drop_index(op.f('ix_donaciones_eliminado'), table_name='donaciones')
    op.drop_index(op.f('ix_donaciones_concepto_id'), table_name='donaciones')
    op.drop_index(op.f('ix_donaciones_campania_id'), table_name='donaciones')
    op.drop_table('donaciones')
    op.drop_index(op.f('ix_cuotas_anuales_miembro_id'), table_name='cuotas_anuales')
    op.drop_index(op.f('ix_cuotas_anuales_estado_codigo'), table_name='cuotas_anuales')
    op.drop_index(op.f('ix_cuotas_anuales_eliminado'), table_name='cuotas_anuales')
    op.drop_index(op.f('ix_cuotas_anuales_ejercicio'), table_name='cuotas_anuales')
    op.drop_index(op.f('ix_cuotas_anuales_agrupacion_id'), table_name='cuotas_anuales')
    op.drop_table('cuotas_anuales')
    op.drop_index(op.f('ix_usuarios_roles_usuario_id'), table_name='usuarios_roles')
    op.drop_index(op.f('ix_usuarios_roles_rol_id'), table_name='usuarios_roles')
    op.drop_index(op.f('ix_usuarios_roles_eliminado'), table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_tipos_notificacion_eliminado'), table_name='tipos_notificacion')
    op.drop_index(op.f('ix_tipos_notificacion_codigo'), table_name='tipos_notificacion')
    op.drop_index(op.f('ix_tipos_notificacion_categoria'), table_name='tipos_notificacion')
    op.drop_index(op.f('ix_tipos_notificacion_activo'), table_name='tipos_notificacion')
    op.drop_table('tipos_notificacion')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_token'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_refresh_token'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_fecha_expiracion'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_eliminado'), table_name='sesiones')
    op.drop_index(op.f('ix_sesiones_activa'), table_name='sesiones')
    op.drop_table('sesiones')
    op.drop_index(op.f('ix_reglas_validacion_config_eliminado'), table_name='reglas_validacion_config')
    op.drop_index(op.f('ix_reglas_validacion_config_config_clave'), table_name='reglas_validacion_config')
    op.drop_table('reglas_validacion_config')
    op.drop_index(op.f('ix_paises_nombre'), table_name='paises')
    op.drop_index(op.f('ix_paises_eliminado'), table_name='paises')
    op.drop_index(op.f('ix_paises_codigo'), table_name='paises')
    op.drop_index(op.f('ix_paises_activo'), table_name='paises')
    op.drop_table('paises')
    op.drop_index(op.f('ix_ips_bloqueadas_ip_address'), table_name='ips_bloqueadas')
    op.drop_index(op.f('ix_ips_bloqueadas_fecha_desbloqueo'), table_name='ips_bloqueadas')
    op.drop_index(op.f('ix_ips_bloqueadas_eliminado'), table_name='ips_bloqueadas')
    op.drop_table('ips_bloqueadas')
    op.drop_index(op.f('ix_intentos_acceso_usuario_id'), table_name='intentos_acceso')
    op.drop_index(op.f('ix_intentos_acceso_ip_address'), table_name='intentos_acceso')
    op.drop_index(op.f('ix_intentos_acceso_identificador'), table_name='intentos_acceso')
    op.drop_index(op.f('ix_intentos_acceso_fecha_intento'), table_name='intentos_acceso')
    op.drop_index(op.f('ix_intentos_acceso_exitoso'), table_name='intentos_acceso')
    op.drop_index(op.f('ix_intentos_acceso_eliminado'), table_name='intentos_acceso')
    op.drop_table('intentos_acceso')
    op.drop_index(op.f('ix_importes_cuota_anio_eliminado'), table_name='importes_cuota_anio')
    op.drop_index(op.f('ix_importes_cuota_anio_ejercicio'), table_name='importes_cuota_anio')
    op.drop_table('importes_cuota_anio')
    op.drop_index(op.f('ix_historial_seguridad_usuario_id'), table_name='historial_seguridad')
    op.drop_index(op.f('ix_historial_seguridad_ip_address'), table_name='historial_seguridad')
    op.drop_index(op.f('ix_historial_seguridad_fecha_evento'), table_name='historial_seguridad')
    op.drop_index(op.f('ix_historial_seguridad_evento_tipo'), table_name='historial_seguridad')
    op.drop_index(op.f('ix_historial_seguridad_eliminado'), table_name='historial_seguridad')
    op.drop_table('historial_seguridad')
    op.drop_index(op.f('ix_historial_estados_fecha_cambio'), table_name='historial_estados')
    op.drop_index(op.f('ix_historial_estados_entidad_tipo'), table_name='historial_estados')
    op.drop_index(op.f('ix_historial_estados_entidad_id'), table_name='historial_estados')
    op.drop_index(op.f('ix_historial_estados_eliminado'), table_name='historial_estados')
    op.drop_table('historial_estados')
    op.drop_index(op.f('ix_estados_tarea_eliminado'), table_name='estados_tarea')
    op.drop_index(op.f('ix_estados_tarea_codigo'), table_name='estados_tarea')
    op.drop_index(op.f('ix_estados_tarea_activo'), table_name='estados_tarea')
    op.drop_table('estados_tarea')
    op.drop_index(op.f('ix_estados_remesa_eliminado'), table_name='estados_remesa')
    op.drop_index(op.f('ix_estados_remesa_codigo'), table_name='estados_remesa')
    op.drop_index(op.f('ix_estados_remesa_activo'), table_name='estados_remesa')
    op.drop_table('estados_remesa')
    op.drop_index(op.f('ix_estados_planificacion_eliminado'), table_name='estados_planificacion')
    op.drop_index(op.f('ix_estados_planificacion_codigo'), table_name='estados_planificacion')
    op.drop_index(op.f('ix_estados_planificacion_activo'), table_name='estados_planificacion')
    op.drop_table('estados_planificacion')
    op.drop_index(op.f('ix_estados_participante_eliminado'), table_name='estados_participante')
    op.drop_index(op.f('ix_estados_participante_codigo'), table_name='estados_participante')
    op.drop_index(op.f('ix_estados_participante_activo'), table_name='estados_participante')
    op.drop_table('estados_participante')
    op.drop_index(op.f('ix_estados_orden_cobro_eliminado'), table_name='estados_orden_cobro')
    op.drop_index(op.f('ix_estados_orden_cobro_codigo'), table_name='estados_orden_cobro')
    op.drop_index(op.f('ix_estados_orden_cobro_activo'), table_name='estados_orden_cobro')
    op.drop_table('estados_orden_cobro')
    op.drop_index(op.f('ix_estados_donacion_eliminado'), table_name='estados_donacion')
    op.drop_index(op.f('ix_estados_donacion_codigo'), table_name='estados_donacion')
    op.drop_index(op.f('ix_estados_donacion_activo'), table_name='estados_donacion')
    op.drop_table('estados_donacion')
    op.drop_index(op.f('ix_estados_cuota_eliminado'), table_name='estados_cuota')
    op.drop_index(op.f('ix_estados_cuota_codigo'), table_name='estados_cuota')
    op.drop_index(op.f('ix_estados_cuota_activo'), table_name='estados_cuota')
    op.drop_table('estados_cuota')
    op.drop_index(op.f('ix_estados_campania_eliminado'), table_name='estados_campania')
    op.drop_index(op.f('ix_estados_campania_codigo'), table_name='estados_campania')
    op.drop_index(op.f('ix_estados_campania_activo'), table_name='estados_campania')
    op.drop_table('estados_campania')
    op.drop_index(op.f('ix_donaciones_conceptos_eliminado'), table_name='donaciones_conceptos')
    op.drop_index(op.f('ix_donaciones_conceptos_codigo'), table_name='donaciones_conceptos')
    op.drop_index(op.f('ix_donaciones_conceptos_activo'), table_name='donaciones_conceptos')
    op.drop_table('donaciones_conceptos')
    op.drop_index(op.f('ix_configuraciones_eliminado'), table_name='configuraciones')
    op.drop_index(op.f('ix_configuraciones_clave'), table_name='configuraciones')
    op.drop_table('configuraciones')
    op.drop_index(op.f('ix_categorias_partida_eliminado'), table_name='categorias_partida')
    op.drop_index(op.f('ix_categorias_partida_codigo'), table_name='categorias_partida')
    op.drop_index(op.f('ix_categorias_partida_activo'), table_name='categorias_partida')
    op.drop_table('categorias_partida')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_eliminado'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_activo'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
