"""Update models: add profesion/nivel_estudios to Miembro, add tipo_miembro_id to ImporteCuotaAnio, add gastos_gestion to CuotaAnual

Revision ID: 32a0dc295063
Revises: 04ede766081e
Create Date: 2026-01-19 18:40:43.184371
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '32a0dc295063'
down_revision: Union[str, None] = '04ede766081e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuotas_anuales', sa.Column('importe_cuota_anio_id', sa.Uuid(), nullable=True))
    op.add_column('cuotas_anuales', sa.Column('gastos_gestion', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index(op.f('ix_cuotas_anuales_importe_cuota_anio_id'), 'cuotas_anuales', ['importe_cuota_anio_id'], unique=False)
    op.create_foreign_key(None, 'cuotas_anuales', 'miembros', ['miembro_id'], ['id'])
    op.create_foreign_key(None, 'cuotas_anuales', 'agrupaciones_territoriales', ['agrupacion_id'], ['id'])
    op.create_foreign_key(None, 'cuotas_anuales', 'importes_cuota_anio', ['importe_cuota_anio_id'], ['id'])
    op.add_column('importes_cuota_anio', sa.Column('tipo_miembro_id', sa.Uuid(), nullable=False))
    op.add_column('importes_cuota_anio', sa.Column('nombre_cuota', sa.String(length=100), nullable=True))
    op.add_column('importes_cuota_anio', sa.Column('observaciones', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_importes_cuota_anio_ejercicio'), table_name='importes_cuota_anio')
    op.create_index(op.f('ix_importes_cuota_anio_ejercicio'), 'importes_cuota_anio', ['ejercicio'], unique=False)
    op.create_index(op.f('ix_importes_cuota_anio_tipo_miembro_id'), 'importes_cuota_anio', ['tipo_miembro_id'], unique=False)
    op.create_foreign_key(None, 'importes_cuota_anio', 'tipos_miembro', ['tipo_miembro_id'], ['id'])
    op.add_column('miembros', sa.Column('profesion', sa.String(length=255), nullable=True))
    op.add_column('miembros', sa.Column('nivel_estudios', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('miembros', 'nivel_estudios')
    op.drop_column('miembros', 'profesion')
    op.drop_constraint(None, 'importes_cuota_anio', type_='foreignkey')
    op.drop_index(op.f('ix_importes_cuota_anio_tipo_miembro_id'), table_name='importes_cuota_anio')
    op.drop_index(op.f('ix_importes_cuota_anio_ejercicio'), table_name='importes_cuota_anio')
    op.create_index(op.f('ix_importes_cuota_anio_ejercicio'), 'importes_cuota_anio', ['ejercicio'], unique=True)
    op.drop_column('importes_cuota_anio', 'observaciones')
    op.drop_column('importes_cuota_anio', 'nombre_cuota')
    op.drop_column('importes_cuota_anio', 'tipo_miembro_id')
    op.drop_constraint(None, 'cuotas_anuales', type_='foreignkey')
    op.drop_constraint(None, 'cuotas_anuales', type_='foreignkey')
    op.drop_constraint(None, 'cuotas_anuales', type_='foreignkey')
    op.drop_index(op.f('ix_cuotas_anuales_importe_cuota_anio_id'), table_name='cuotas_anuales')
    op.drop_column('cuotas_anuales', 'gastos_gestion')
    op.drop_column('cuotas_anuales', 'importe_cuota_anio_id')
    # ### end Alembic commands ###
