"""add_campania_fk_to_actividades

Revision ID: 564207c255eb
Revises: ce6205f5e089
Create Date: 2026-01-19 19:26:29.576597
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '564207c255eb'
down_revision: Union[str, None] = 'ce6205f5e089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'actividades', 'campanias', ['campania_id'], ['id'])
    op.add_column('estados_actividad', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('estados_actividad', sa.Column('es_inicial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estados_actividad', 'es_inicial')
    op.drop_column('estados_actividad', 'descripcion')
    op.drop_constraint(None, 'actividades', type_='foreignkey')
    # ### end Alembic commands ###
