"""remove_acciones_campania_table

Revision ID: 5c2912c2f427
Revises: 564207c255eb
Create Date: 2026-01-19 19:30:48.347194
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c2912c2f427'
down_revision: Union[str, None] = '564207c255eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acciones_campania_campania_id'), table_name='acciones_campania')
    op.drop_index(op.f('ix_acciones_campania_completada'), table_name='acciones_campania')
    op.drop_index(op.f('ix_acciones_campania_eliminado'), table_name='acciones_campania')
    op.drop_index(op.f('ix_acciones_campania_fecha'), table_name='acciones_campania')
    op.drop_table('acciones_campania')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones_campania',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campania_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora_inicio', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('hora_fin', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('lugar', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('voluntarios_necesarios', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voluntarios_confirmados', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('materiales_necesarios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completada', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_modificacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_eliminacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eliminado', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('creado_por_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('modificado_por_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campania_id'], ['campanias.id'], name=op.f('acciones_campania_campania_id_fkey')),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], name=op.f('acciones_campania_creado_por_id_fkey')),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], name=op.f('acciones_campania_modificado_por_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('acciones_campania_pkey'))
    )
    op.create_index(op.f('ix_acciones_campania_fecha'), 'acciones_campania', ['fecha'], unique=False)
    op.create_index(op.f('ix_acciones_campania_eliminado'), 'acciones_campania', ['eliminado'], unique=False)
    op.create_index(op.f('ix_acciones_campania_completada'), 'acciones_campania', ['completada'], unique=False)
    op.create_index(op.f('ix_acciones_campania_campania_id'), 'acciones_campania', ['campania_id'], unique=False)
    # ### end Alembic commands ###
