"""cargos_roles_nombramiento_usuariorol

Revision ID: 705751a664c9
Revises: a1b2c3d4e5f6
Create Date: 2026-05-15 06:01:54.857910
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '705751a664c9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_unidad_id', sa.Uuid(), nullable=True),
    sa.Column('puede_nominar_igual_nivel', sa.Boolean(), nullable=False),
    sa.Column('requiere_aprobacion', sa.Boolean(), nullable=False),
    sa.Column('cargo_aprobador_id', sa.Uuid(), nullable=True),
    sa.Column('max_simultaneos', sa.Integer(), nullable=False),
    sa.Column('duracion_maxima_meses', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_aprobador_id'], ['cargos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_unidad_id'], ['tipos_unidades_organizativas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_activo'), 'cargos', ['activo'], unique=False)
    op.create_index(op.f('ix_cargos_eliminado'), 'cargos', ['eliminado'], unique=False)
    op.create_index(op.f('ix_cargos_tipo_unidad_id'), 'cargos', ['tipo_unidad_id'], unique=False)
    op.create_table('cargos_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cargo_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_roles_cargo_id'), 'cargos_roles', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_cargos_roles_eliminado'), 'cargos_roles', ['eliminado'], unique=False)
    op.create_index(op.f('ix_cargos_roles_rol_id'), 'cargos_roles', ['rol_id'], unique=False)
    op.drop_index(op.f('ix_acciones_eliminado'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_estado_id'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_fecha_inicio'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_grupo_id'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_iniciativa_id'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_nombre'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_responsable_id'), table_name='actividades')
    op.drop_index(op.f('ix_acciones_tipo_accion_id'), table_name='actividades')
    op.create_index(op.f('ix_actividades_campania_id'), 'actividades', ['campania_id'], unique=False)
    op.create_index(op.f('ix_actividades_eliminado'), 'actividades', ['eliminado'], unique=False)
    op.create_index(op.f('ix_actividades_estado_id'), 'actividades', ['estado_id'], unique=False)
    op.create_index(op.f('ix_actividades_fecha_inicio'), 'actividades', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_actividades_grupo_id'), 'actividades', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_actividades_nombre'), 'actividades', ['nombre'], unique=False)
    op.create_index(op.f('ix_actividades_responsable_id'), 'actividades', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_actividades_tipo_actividad_id'), 'actividades', ['tipo_actividad_id'], unique=False)
    op.add_column('aportaciones_horas', sa.Column('creado_por_id', sa.Uuid(), nullable=True))
    op.add_column('aportaciones_horas', sa.Column('modificado_por_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_aportaciones_horas_eliminado'), 'aportaciones_horas', ['eliminado'], unique=False)
    op.create_foreign_key(None, 'aportaciones_horas', 'usuarios', ['creado_por_id'], ['id'])
    op.create_foreign_key(None, 'aportaciones_horas', 'usuarios', ['modificado_por_id'], ['id'])
    op.add_column('compromisos_presupuestarios', sa.Column('creado_por_id', sa.Uuid(), nullable=True))
    op.add_column('compromisos_presupuestarios', sa.Column('modificado_por_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_compromisos_presupuestarios_eliminado'), 'compromisos_presupuestarios', ['eliminado'], unique=False)
    op.create_foreign_key(None, 'compromisos_presupuestarios', 'usuarios', ['creado_por_id'], ['id'])
    op.create_foreign_key(None, 'compromisos_presupuestarios', 'usuarios', ['modificado_por_id'], ['id'])
    op.drop_index(op.f('ix_grupo_iniciativa_iniciativa_id'), table_name='grupo_iniciativa')
    op.create_index(op.f('ix_grupo_iniciativa_campania_id'), 'grupo_iniciativa', ['campania_id'], unique=False)
    op.add_column('historial_nombramientos', sa.Column('cargo_id', sa.Uuid(), nullable=True))
    op.add_column('historial_nombramientos', sa.Column('estado', sa.String(length=20), server_default='ACTIVO', nullable=False))
    op.add_column('historial_nombramientos', sa.Column('aprobado_por_id', sa.Uuid(), nullable=True))
    op.add_column('historial_nombramientos', sa.Column('fecha_aprobacion', sa.Date(), nullable=True))
    op.alter_column('historial_nombramientos', 'rol_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_hist_nombr_rol'), table_name='historial_nombramientos')
    op.create_index('ix_hist_nombr_cargo', 'historial_nombramientos', ['cargo_id'], unique=False)
    op.create_index('ix_hist_nombr_estado', 'historial_nombramientos', ['estado'], unique=False)
    op.create_index(op.f('ix_historial_nombramientos_cargo_id'), 'historial_nombramientos', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_historial_nombramientos_estado'), 'historial_nombramientos', ['estado'], unique=False)
    op.create_foreign_key(None, 'historial_nombramientos', 'cargos', ['cargo_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'historial_nombramientos', 'usuarios', ['aprobado_por_id'], ['id'], ondelete='SET NULL')
    op.add_column('participaciones', sa.Column('actividad_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_participaciones_accion_id'), table_name='participaciones')
    op.create_index(op.f('ix_participaciones_actividad_id'), 'participaciones', ['actividad_id'], unique=False)
    op.drop_constraint(op.f('participaciones_accion_id_fkey'), 'participaciones', type_='foreignkey')
    op.create_foreign_key(None, 'participaciones', 'actividades', ['actividad_id'], ['id'])
    op.drop_column('participaciones', 'accion_id')
    op.add_column('requisitos_recurso', sa.Column('creado_por_id', sa.Uuid(), nullable=True))
    op.add_column('requisitos_recurso', sa.Column('modificado_por_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_requisitos_recurso_eliminado'), 'requisitos_recurso', ['eliminado'], unique=False)
    op.create_foreign_key(None, 'requisitos_recurso', 'usuarios', ['modificado_por_id'], ['id'])
    op.create_foreign_key(None, 'requisitos_recurso', 'usuarios', ['creado_por_id'], ['id'])
    op.drop_index(op.f('ix_tareas_accion_id'), table_name='tareas')
    op.create_index(op.f('ix_tareas_actividad_id'), 'tareas', ['actividad_id'], unique=False)
    op.add_column('usuarios_roles', sa.Column('nombramiento_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_usuarios_roles_nombramiento_id'), 'usuarios_roles', ['nombramiento_id'], unique=False)
    op.create_foreign_key(None, 'usuarios_roles', 'historial_nombramientos', ['nombramiento_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios_roles', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_roles_nombramiento_id'), table_name='usuarios_roles')
    op.drop_column('usuarios_roles', 'nombramiento_id')
    op.drop_index(op.f('ix_tareas_actividad_id'), table_name='tareas')
    op.create_index(op.f('ix_tareas_accion_id'), 'tareas', ['actividad_id'], unique=False)
    op.drop_constraint(None, 'requisitos_recurso', type_='foreignkey')
    op.drop_constraint(None, 'requisitos_recurso', type_='foreignkey')
    op.drop_index(op.f('ix_requisitos_recurso_eliminado'), table_name='requisitos_recurso')
    op.drop_column('requisitos_recurso', 'modificado_por_id')
    op.drop_column('requisitos_recurso', 'creado_por_id')
    op.add_column('participaciones', sa.Column('accion_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'participaciones', type_='foreignkey')
    op.create_foreign_key(op.f('participaciones_accion_id_fkey'), 'participaciones', 'actividades', ['accion_id'], ['id'])
    op.drop_index(op.f('ix_participaciones_actividad_id'), table_name='participaciones')
    op.create_index(op.f('ix_participaciones_accion_id'), 'participaciones', ['accion_id'], unique=False)
    op.drop_column('participaciones', 'actividad_id')
    op.drop_constraint(None, 'historial_nombramientos', type_='foreignkey')
    op.drop_constraint(None, 'historial_nombramientos', type_='foreignkey')
    op.drop_index(op.f('ix_historial_nombramientos_estado'), table_name='historial_nombramientos')
    op.drop_index(op.f('ix_historial_nombramientos_cargo_id'), table_name='historial_nombramientos')
    op.drop_index('ix_hist_nombr_estado', table_name='historial_nombramientos')
    op.drop_index('ix_hist_nombr_cargo', table_name='historial_nombramientos')
    op.create_index(op.f('ix_hist_nombr_rol'), 'historial_nombramientos', ['rol_id'], unique=False)
    op.alter_column('historial_nombramientos', 'rol_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('historial_nombramientos', 'fecha_aprobacion')
    op.drop_column('historial_nombramientos', 'aprobado_por_id')
    op.drop_column('historial_nombramientos', 'estado')
    op.drop_column('historial_nombramientos', 'cargo_id')
    op.drop_index(op.f('ix_grupo_iniciativa_campania_id'), table_name='grupo_iniciativa')
    op.create_index(op.f('ix_grupo_iniciativa_iniciativa_id'), 'grupo_iniciativa', ['campania_id'], unique=False)
    op.drop_constraint(None, 'compromisos_presupuestarios', type_='foreignkey')
    op.drop_constraint(None, 'compromisos_presupuestarios', type_='foreignkey')
    op.drop_index(op.f('ix_compromisos_presupuestarios_eliminado'), table_name='compromisos_presupuestarios')
    op.drop_column('compromisos_presupuestarios', 'modificado_por_id')
    op.drop_column('compromisos_presupuestarios', 'creado_por_id')
    op.drop_constraint(None, 'aportaciones_horas', type_='foreignkey')
    op.drop_constraint(None, 'aportaciones_horas', type_='foreignkey')
    op.drop_index(op.f('ix_aportaciones_horas_eliminado'), table_name='aportaciones_horas')
    op.drop_column('aportaciones_horas', 'modificado_por_id')
    op.drop_column('aportaciones_horas', 'creado_por_id')
    op.drop_index(op.f('ix_actividades_tipo_actividad_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_responsable_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_nombre'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_grupo_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha_inicio'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_estado_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_eliminado'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_campania_id'), table_name='actividades')
    op.create_index(op.f('ix_acciones_tipo_accion_id'), 'actividades', ['tipo_actividad_id'], unique=False)
    op.create_index(op.f('ix_acciones_responsable_id'), 'actividades', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_acciones_nombre'), 'actividades', ['nombre'], unique=False)
    op.create_index(op.f('ix_acciones_iniciativa_id'), 'actividades', ['campania_id'], unique=False)
    op.create_index(op.f('ix_acciones_grupo_id'), 'actividades', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_acciones_fecha_inicio'), 'actividades', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_acciones_estado_id'), 'actividades', ['estado_id'], unique=False)
    op.create_index(op.f('ix_acciones_eliminado'), 'actividades', ['eliminado'], unique=False)
    op.drop_index(op.f('ix_cargos_roles_rol_id'), table_name='cargos_roles')
    op.drop_index(op.f('ix_cargos_roles_eliminado'), table_name='cargos_roles')
    op.drop_index(op.f('ix_cargos_roles_cargo_id'), table_name='cargos_roles')
    op.drop_table('cargos_roles')
    op.drop_index(op.f('ix_cargos_tipo_unidad_id'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_eliminado'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_activo'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
