"""add_estado_id_to_miembros

Revision ID: ce6205f5e089
Revises: 32a0dc295063
Create Date: 2026-01-19 19:00:28.995181
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ce6205f5e089'
down_revision: Union[str, None] = '32a0dc295063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_miembro',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estados_miembro_activo'), 'estados_miembro', ['activo'], unique=False)
    op.create_index(op.f('ix_estados_miembro_codigo'), 'estados_miembro', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_miembro_eliminado'), 'estados_miembro', ['eliminado'], unique=False)
    op.add_column('miembros', sa.Column('estado_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_miembros_estado_id'), 'miembros', ['estado_id'], unique=False)
    op.create_foreign_key(None, 'miembros', 'estados_miembro', ['estado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'miembros', type_='foreignkey')
    op.drop_index(op.f('ix_miembros_estado_id'), table_name='miembros')
    op.drop_column('miembros', 'estado_id')
    op.drop_index(op.f('ix_estados_miembro_eliminado'), table_name='estados_miembro')
    op.drop_index(op.f('ix_estados_miembro_codigo'), table_name='estados_miembro')
    op.drop_index(op.f('ix_estados_miembro_activo'), table_name='estados_miembro')
    op.drop_table('estados_miembro')
    # ### end Alembic commands ###
