"""campanas_presupuesto_trabajo_documentos

Revision ID: f7cbe6981805
Revises: j5k6l7m8n9o0
Create Date: 2026-05-16 19:05:59.803075
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f7cbe6981805'
down_revision: Union[str, None] = 'j5k6l7m8n9o0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_actividad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actividad_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamanyo', sa.BigInteger(), nullable=True),
    sa.Column('tipo_doc', sa.String(length=20), nullable=False),
    sa.Column('subido_por_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_actividad_actividad_id'), 'documentos_actividad', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_documentos_actividad_eliminado'), 'documentos_actividad', ['eliminado'], unique=False)
    op.create_table('partidas_presupuesto_actividad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actividad_id', sa.Uuid(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('importe_estimado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('importe_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tipo_partida', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_presupuesto_actividad_actividad_id'), 'partidas_presupuesto_actividad', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_partidas_presupuesto_actividad_eliminado'), 'partidas_presupuesto_actividad', ['eliminado'], unique=False)
    op.create_table('registros_trabajo_actividad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actividad_id', sa.Uuid(), nullable=False),
    sa.Column('miembro_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('horas', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_trabajo_actividad_actividad_id'), 'registros_trabajo_actividad', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_registros_trabajo_actividad_eliminado'), 'registros_trabajo_actividad', ['eliminado'], unique=False)
    op.create_index(op.f('ix_registros_trabajo_actividad_miembro_id'), 'registros_trabajo_actividad', ['miembro_id'], unique=False)
    op.create_table('documentos_partida',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('partida_actividad_id', sa.Uuid(), nullable=True),
    sa.Column('partida_campania_id', sa.Uuid(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamanyo', sa.BigInteger(), nullable=True),
    sa.Column('tipo_doc', sa.String(length=20), nullable=False),
    sa.Column('subido_por_id', sa.Uuid(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['partida_actividad_id'], ['partidas_presupuesto_actividad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partida_campania_id'], ['partidas_presupuesto_campania.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_partida_eliminado'), 'documentos_partida', ['eliminado'], unique=False)
    op.create_index(op.f('ix_documentos_partida_partida_actividad_id'), 'documentos_partida', ['partida_actividad_id'], unique=False)
    op.create_index(op.f('ix_documentos_partida_partida_campania_id'), 'documentos_partida', ['partida_campania_id'], unique=False)
    op.drop_column('campanias', 'meta_recaudacion')
    op.drop_column('campanias', 'meta_firmas')
    op.drop_column('campanias', 'meta_participantes')
    op.create_index(op.f('ix_canales_difusion_campania_canal_id'), 'canales_difusion_campania', ['canal_id'], unique=False)
    op.alter_column('metas_campania', 'valor_planificado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.create_index(op.f('ix_metas_campania_tipo_meta_id'), 'metas_campania', ['tipo_meta_id'], unique=False)
    op.alter_column('partidas_presupuesto_campania', 'importe_estimado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('plantilla_actividades', 'duracion_dias',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_plantilla_actividades_tipo_actividad_id'), 'plantilla_actividades', ['tipo_actividad_id'], unique=False)
    op.create_index(op.f('ix_plantilla_metas_tipo_meta_id'), 'plantilla_metas', ['tipo_meta_id'], unique=False)
    op.alter_column('plantilla_partidas', 'importe_estimado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('plantilla_tareas', 'horas_estimadas',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.drop_constraint(op.f('plantillas_campania_tipo_campania_id_key'), 'plantillas_campania', type_='unique')
    op.create_index(op.f('ix_plantillas_campania_tipo_campania_id'), 'plantillas_campania', ['tipo_campania_id'], unique=True)
    op.drop_constraint(op.f('plantillas_email_codigo_key'), 'plantillas_email', type_='unique')
    op.drop_index(op.f('ix_plantillas_email_codigo'), table_name='plantillas_email')
    op.create_index(op.f('ix_plantillas_email_codigo'), 'plantillas_email', ['codigo'], unique=True)
    op.drop_column('roles_participante', 'es_inmutable')
    op.create_index(op.f('ix_tipos_canal_difusion_activo'), 'tipos_canal_difusion', ['activo'], unique=False)
    op.create_index(op.f('ix_tipos_meta_campania_activo'), 'tipos_meta_campania', ['activo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_meta_campania_activo'), table_name='tipos_meta_campania')
    op.drop_index(op.f('ix_tipos_canal_difusion_activo'), table_name='tipos_canal_difusion')
    op.add_column('roles_participante', sa.Column('es_inmutable', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_plantillas_email_codigo'), table_name='plantillas_email')
    op.create_index(op.f('ix_plantillas_email_codigo'), 'plantillas_email', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('plantillas_email_codigo_key'), 'plantillas_email', ['codigo'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_plantillas_campania_tipo_campania_id'), table_name='plantillas_campania')
    op.create_unique_constraint(op.f('plantillas_campania_tipo_campania_id_key'), 'plantillas_campania', ['tipo_campania_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('plantilla_tareas', 'horas_estimadas',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=1),
               existing_nullable=True)
    op.alter_column('plantilla_partidas', 'importe_estimado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_plantilla_metas_tipo_meta_id'), table_name='plantilla_metas')
    op.drop_index(op.f('ix_plantilla_actividades_tipo_actividad_id'), table_name='plantilla_actividades')
    op.alter_column('plantilla_actividades', 'duracion_dias',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('partidas_presupuesto_campania', 'importe_estimado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_metas_campania_tipo_meta_id'), table_name='metas_campania')
    op.alter_column('metas_campania', 'valor_planificado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_canales_difusion_campania_canal_id'), table_name='canales_difusion_campania')
    op.add_column('campanias', sa.Column('meta_participantes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('campanias', sa.Column('meta_firmas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('campanias', sa.Column('meta_recaudacion', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documentos_partida_partida_campania_id'), table_name='documentos_partida')
    op.drop_index(op.f('ix_documentos_partida_partida_actividad_id'), table_name='documentos_partida')
    op.drop_index(op.f('ix_documentos_partida_eliminado'), table_name='documentos_partida')
    op.drop_table('documentos_partida')
    op.drop_index(op.f('ix_registros_trabajo_actividad_miembro_id'), table_name='registros_trabajo_actividad')
    op.drop_index(op.f('ix_registros_trabajo_actividad_eliminado'), table_name='registros_trabajo_actividad')
    op.drop_index(op.f('ix_registros_trabajo_actividad_actividad_id'), table_name='registros_trabajo_actividad')
    op.drop_table('registros_trabajo_actividad')
    op.drop_index(op.f('ix_partidas_presupuesto_actividad_eliminado'), table_name='partidas_presupuesto_actividad')
    op.drop_index(op.f('ix_partidas_presupuesto_actividad_actividad_id'), table_name='partidas_presupuesto_actividad')
    op.drop_table('partidas_presupuesto_actividad')
    op.drop_index(op.f('ix_documentos_actividad_eliminado'), table_name='documentos_actividad')
    op.drop_index(op.f('ix_documentos_actividad_actividad_id'), table_name='documentos_actividad')
    op.drop_table('documentos_actividad')
    # ### end Alembic commands ###
