"""create historial_nombramientos and coordinaciones_territoriales tables

Revision ID: m009_create_hist_nombr_y_coordinaciones
Revises: m008_add_password_reset_token
Create Date: 2026-05-06 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'm009_create_hist_nombr_y_coordinaciones'
down_revision: Union[str, None] = 'm008_add_password_reset_token'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinaciones_territoriales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('miembro_id', sa.Uuid(), nullable=False),
    sa.Column('agrupacion_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones_territoriales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinaciones_territoriales_agrupacion_id'), 'coordinaciones_territoriales', ['agrupacion_id'], unique=False)
    op.create_index(op.f('ix_coordinaciones_territoriales_eliminado'), 'coordinaciones_territoriales', ['eliminado'], unique=False)
    op.create_index(op.f('ix_coordinaciones_territoriales_miembro_id'), 'coordinaciones_territoriales', ['miembro_id'], unique=False)

    op.create_table('historial_nombramientos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('miembro_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_cargo_id', sa.Uuid(), nullable=False),
    sa.Column('agrupacion_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('tipo_origen', sa.String(length=50), nullable=True),
    sa.Column('origen_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creado_por_id', sa.Uuid(), nullable=True),
    sa.Column('modificado_por_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones_territoriales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modificado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_cargo_id'], ['tipos_cargo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_nombramientos_agrupacion_id'), 'historial_nombramientos', ['agrupacion_id'], unique=False)
    op.create_index(op.f('ix_historial_nombramientos_eliminado'), 'historial_nombramientos', ['eliminado'], unique=False)
    op.create_index(op.f('ix_historial_nombramientos_miembro_id'), 'historial_nombramientos', ['miembro_id'], unique=False)
    op.create_index('ix_hist_nombr_miembro', 'historial_nombramientos', ['miembro_id'], unique=False)
    op.create_index('ix_hist_nombr_agrupacion', 'historial_nombramientos', ['agrupacion_id'], unique=False)
    op.create_index('ix_hist_nombr_vigente', 'historial_nombramientos', ['miembro_id', 'fecha_inicio', 'fecha_fin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hist_nombr_vigente', table_name='historial_nombramientos')
    op.drop_index('ix_hist_nombr_agrupacion', table_name='historial_nombramientos')
    op.drop_index('ix_hist_nombr_miembro', table_name='historial_nombramientos')
    op.drop_index(op.f('ix_historial_nombramientos_miembro_id'), table_name='historial_nombramientos')
    op.drop_index(op.f('ix_historial_nombramientos_eliminado'), table_name='historial_nombramientos')
    op.drop_index(op.f('ix_historial_nombramientos_agrupacion_id'), table_name='historial_nombramientos')
    op.drop_table('historial_nombramientos')
    op.drop_index(op.f('ix_coordinaciones_territoriales_miembro_id'), table_name='coordinaciones_territoriales')
    op.drop_index(op.f('ix_coordinaciones_territoriales_eliminado'), table_name='coordinaciones_territoriales')
    op.drop_index(op.f('ix_coordinaciones_territoriales_agrupacion_id'), table_name='coordinaciones_territoriales')
    op.drop_table('coordinaciones_territoriales')
    # ### end Alembic commands ###
